// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpoC0dvzTLnNtAE-gdO7RPQwyZ78EBAzQ',
    appId: '1:768848997584:web:5a943283446d64f8d942d5',
    messagingSenderId: '768848997584',
    projectId: 'epilog-1fa6c',
    authDomain: 'epilog-1fa6c.firebaseapp.com',
    storageBucket: 'epilog-1fa6c.appspot.com',
    measurementId: 'G-7FKJSC1P1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMn8Ejj9nSsl7xyNCfomXZgosqQLMGRXk',
    appId: '1:768848997584:android:c8a61253aa47cb52d942d5',
    messagingSenderId: '768848997584',
    projectId: 'epilog-1fa6c',
    storageBucket: 'epilog-1fa6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmMZ8simKVUrizNE8TKmJzu9SDIb3uZNs',
    appId: '1:768848997584:ios:80fd857c0e727555d942d5',
    messagingSenderId: '768848997584',
    projectId: 'epilog-1fa6c',
    storageBucket: 'epilog-1fa6c.appspot.com',
    iosClientId: '768848997584-k85v4b58j59cagnnqd1fvdsm85m3r69g.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmMZ8simKVUrizNE8TKmJzu9SDIb3uZNs',
    appId: '1:768848997584:ios:80fd857c0e727555d942d5',
    messagingSenderId: '768848997584',
    projectId: 'epilog-1fa6c',
    storageBucket: 'epilog-1fa6c.appspot.com',
    iosClientId: '768848997584-k85v4b58j59cagnnqd1fvdsm85m3r69g.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );
}
