/// Flutter icons List_alt_filled
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  List_alt_filled
///      fonts:
///       - asset: fonts/List_alt_filled.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class List_alt_filled {
  List_alt_filled._();

  static const _kFontFam = 'List_alt_filled';
  static const String? _kFontPkg = null;

  static const IconData filled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
